### ISSUE TITLE
DOTweenSettings do Reset if do Reimport All

### ISSUE THREAD

**Issue by LessTergy** [Demigiant/dotween#280]
Everytime when I do Reimport All or just clone repository without Unity cache, my DOTweenSettings do Reset. 
If I use custom location path for settings file, DOTween just ignore it, and creates another one with default settings.
First time I was thinking that it is my custom DOTween folder path (Assets/3rd-Party/DOTween) but in default folder I still have this annoying issue.

My custom settings
- Physics off
- Physics2D off

DOTween 1.2.155
Unity 2018.3.0f2

**Comment by Demigiant** [comment]
Hi,

I just noticed this recently and was testing it out also on the latest Unity to be sure I fixed it. Could you give [this version](http://dotween.demigiant.com/tmp/DOTween_1_2_160.zip) a try and let me know if it doesn't reset anymore (and sorry for the inconvenience).

Cheers,
Daniele

**Comment by LessTergy** [comment]
Thank you for quick reply!
Maybe is it better to wait stable release version? We can wait.

**Comment by Demigiant** [comment]
Should release it a short while then, I delayed the release mostly because of other features I was working on :P

**Comment by Demigiant** [comment]
Agh, sorry, I released it a few days ago and forgot to warn you here. [Here's an even newer version](http://dotween.demigiant.com/download.php) that fixes it :)

**Comment by LessTergy** [comment]
Cool, thank you! :)

**Comment by stopiccot** [comment]
Still an issue for me. I've added DOTween (1.2.235) to my unity project (2018.4.0). Then I had unselected Audio, Physics and Physics2D modules. Then I've commited changes to DOTweenModuleXXX.cs files. After than I ran `git clean -xdf && git reset --hard` to reset my repo to initial state. After importing clean project I see the Audio, Physics and Physics2D modules enabled again and DOTweenModuleXXX.cs files are changed back.

**Comment by stopiccot** [comment]
Ok, my bad, seems like DOTweenSettings.asset wasn't saved to filesystem and thus wasn't commited to git before clean. I think it may be reasonable to force save DOTweenSettings.asset each time user changes module settings.

**Comment by Demigiant** [comment]
Ah, I usually don't force saving but just mark the asset dirty, so when the project is saved that will be saved too. I follow this approach because that's Unity's own approach, which means File > Save Project is always your friend before a commit :P
