### ISSUE TITLE
Improve the exception message thrown by DOTween

### ISSUE THREAD

**Issue by wilczarzgit** [Demigiant/dotween#371]
Quite often I find myself debugging this error thrown from DOTween:

> MissingReferenceException: The object of type 'RectTransform' has been destroyed but you are still trying to access it. Your script should either check if it is null or you should not destroy the object.

Obviously, some object was removed while the tween is still running, so it's my fault. But can you please make it easier to debug this issue by improving the log message? For example, printing out what tween throws that exception, or even better what was the name of the target's game object? This would help A LOT!

**Comment by Demigiant** [comment]
A tween has no idea of what the target's gameObject is. But, if you want to store the extra data for debug and better log messages, in recent versions of DOTween you can already activate a DEBUG MODE from DOTween Utility Panel (last option in the Preferences tab), which will do just that :)

**Comment by wilczarzgit** [comment]
I am not trying to dimnish DEBUG MODE (seems like a great tool!), but put yourself in the shoes of a coder. You have a faulty tween somewhere, and you can't track it down. Using DEBUG MODE means you have to attach diagnostic information manually to every single tween in the code to be able to track it down. This is a lot of work! 

Please think about a quick out-of the box solution. Off the top of my head, if a target is a component, then store gameObject name as tween.gameObjectName = ((Component) target).gameObject.name and print it to console attached to MissingReference exception. Something like (Last game object name was: XXX). I know it is clunky but realistically, it would be a life savior for me dozen times. I am willing to bet this is the most common exception for other DOTween users as well. 

I just realized that this simple thing is my mostly desired feature of DOTween and it makes me a bit sad you closed this issue so quickly :( Please think abut it again.

**Comment by Demigiant** [comment]
Wil, I closed the issue because what you're asking is exactly what the DOTween's DEBUG MODE does. It auto-attaches extra information to the tween and then logs a clearer log that includes the involved GameObject's name in case errors happen, without requiring any extra manual work other than setting the preference in DOTween's Utility Panel.

Did you check it out? Am I missing something?

![image](https://user-images.githubusercontent.com/8322877/74236491-9a5ec780-4cd1-11ea-9cd1-bb6c041fa0e2.png)

**Comment by wilczarzgit** [comment]
Ah, it happens automatically! Perfect. 
I did check it out but my bug was fixed before that so I never saw any exception with DEBUG MODE.
I thought I had to attach the data manually somehow. I guess I need to read more carefully.

Thanks for providing this feature!

**Comment by ariok** [comment]
I'm sorry for necro this issue. Even activating the DebugMode and checking the "Store GameObject'ID" I don't see any specific info about the GameObject that raised the warning. I'm still seeing the same output in the console. Am I missing something? 
(I've Default log behaviour and safe mode activated)

**Comment by lopezmramon** [comment]
In case anyone appears and still has the issue the previous commenter had - SafeMode must be active, plus Verbose should be enabled. Works well.

**Comment by Neon-Specter** [comment]
Even with debug mode + safe mode + verbose logging, I still don't see any additional info about the source of the error.
